name: Test slack approval

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  approval2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - run: |
            npm install
      - name: slack-approval
        uses: ./
        env:
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP__AFRESHY__APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP__AFRESHY__BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_APP__AFRESHY__SIGNING_SECRET }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK__CHANNEL_ID__NOISE }}
          APPROVERS: ""
          REQUEST_REASON: "gha-slack-approval testing"
          ENVIRONMENT: "`${{ github.ref_name }}`"
          URL: <${{ github.server_url }}/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.event.after }}|diff>
        timeout-minutes: 120
      - name: slack-approval
        uses: ./
        env:
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP__AFRESHY__APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP__AFRESHY__BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_APP__AFRESHY__SIGNING_SECRET }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK__CHANNEL_ID__NOISE }}
          APPROVERS: ""
          REQUEST_REASON: "gha-slack-approval testing timeout behavior (1 minute timeout)"
          ENVIRONMENT: "`${{ github.ref_name }}`"
          URL: <${{ github.server_url }}/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.event.after }}|diff>
        timeout-minutes: 1
      
